### ISSUE TITLE
Support for style parameter on transform-imports plugin

### ISSUE THREAD

**Issue by AlphaByte02** [swc-project/plugins#106]
A feature request to add optional parameter for the style import along with the transform.
Something similar to what [swc-plugin-transform-import](https://github.com/ankitchouhan1020/swc-plugin-transform-import) and [babel-plugin-import](https://github.com/umijs/babel-plugin-import) already do.

This would solve the problem with many components library (like antd or MUI).

Thanks for the hard work.

**Comment by kdy1** [comment]
I think https://github.com/swc-project/plugins/pull/196 fixed this
