### ISSUE TITLE
plugin-styled-components generate different className for snapshot

### ISSUE THREAD

**Issue by dmaklygin** [swc-project/plugins#136]
We have tests that are written some time ago.
Such tests use `toMatchSnapshot` for React components.
We used to use: Jest + Babel + `babel-plugin-styled-components`.

And after switching to Jest with `@swc/jest` + `@swc/plugin-styled-components`, I've got another snapshot than before:

Screenshot Before:

```
...
.c0.c0:visited {
  color: inherit;
}

      <a
        _css="&&:visited{color:inherit;}"
        class="%some_insignificant_class_names% MenuLink___StyledLink-sc-10agu55 c0 "
        data-testid="downloadPdfUrl"
        href="example.com/test"
        role="menuitem"
        tabindex="-1"
      >
...
```

But after adopting @swc/jest, I've got another snapshot:

```
.c0.c0:visited {
  color: inherit;
}

 <a
    -         _css="&&:visited{color:inherit;}"
              aria-disabled="false"
    -         class="%some_insignificant_class_names% MenuLink___StyledLink-sc-10agu55 c0"
    +         class="%some_insignificant_class_names% MenuLink___StyledLink-sc-0 c0"
              data-testid="downloadPdfUrl"
              href="example.com/test"
              role="menuitem"
              tabindex="-1"
            >

```

I was playing with the settings to make it the same, but no result so far.
As I can see, the new plugin does not generate `hash` for className + does not keep `_css` prop

my Jest setting is:

```
transform: {
    '^.+\\.(t|j)sx?$': [
      '@swc/jest',
      {
        module: {
          type: 'es6',
        },
        jsc: {
          transform: {
            react: {
              runtime: 'automatic',
              useBuiltins: true,
            },
            optimizer: {
              simplify: false,
            },
          },
          parser: {
            decorators: true,
            dynamicImport: true,
            syntax: 'typescript',
            tsx: true,
          },
          experimental: {
            plugins: [
              [
                '@swc/plugin-styled-components',
                {
                  displayName: true
                },
              ],
            ],
          },
        },
      },
    ],
  },
```

**Comment by dennys-bd** [comment]
Here it did generate a different hash, which is ok
But on C.I it did generate a different hash again, so my snapshots don't pass on circleCI

Commit changing snapshot
<div
-  className="EventDateLocation__Wrapper-sc-1r92gat-0 flVJln"
+  className="EventDateLocation__Wrapper-sc-e2ac41d5-0 eWfchw"
>

CircleCI comparison
  <div
-   className="EventDateLocation__Wrapper-sc-e2ac41d5-0 eWfchw"
+   className="EventDateLocation__Wrapper-sc-503c113a-0 emkUli"
  >

``` package.lock.json
"@swc/core": "1.3.27",
"@swc/jest": "0.2.24",
"@swc/plugin-styled-components": "1.5.37",
```
