### ISSUE TITLE
styled-components minify doesn't work with provided target

### ISSUE THREAD

**Issue by huv1k** [swc-project/plugins#143]
Hey, I was trying out `@swc/plugin-styled-components`, but compiled output with selected target `es2020` doesn't remove comments and white spaces. Here is [repo](https://github.com/huv1k/swc-styled-components-target) with reproduction. 

For input, I used [input](https://github.com/swc-project/plugins/blob/main/packages/styled-components/transform/tests/fixtures/.minify-css-to-use-without-transpilation/code.js) from tests and output is like [this](https://github.com/huv1k/swc-styled-components-target/blob/master/out.js). Comments are still presented and output inside template literals is not minified. 

## How to reproduce
1. Clone repro
2. `yarn install`
3. `yarn run compile`

**Comment by phiter** [comment]
Yeah, I'm trying out the plugin and minification doesn't seem to be working yet. The file is empty:

https://github.com/swc-project/plugins/blob/60bd4ffdfca432878fd36acc7b7fcfee6fb7a997/packages/styled-components/transform/src/visitors/minify.rs#L1

@kdy1 sorry for pinging you. Are there any plans to implement this?

**Comment by kwonoj** [comment]
There are not immediate plans as we have high priorities. Happy to accept PR.

**Comment by phiter** [comment]
Oh this is great! When will this change be available as a new version? @kdy1
