### ISSUE TITLE
Can we publish the swc_plugin_loadable_components to crates.io that we can import it when swc_core@lastest.

### ISSUE THREAD

**Issue by GiveMe-A-Name** [swc-project/plugins#166]
Wish use the swc_plugin_loadable_components crates lastest in rust.

**Comment by kdy1** [comment]
What's your usecase?

**Comment by GiveMe-A-Name** [comment]
Like `nextjs`, we can interate the swc plugins as a binary package that avoid the cost of `wasm`, initial size, performance and so on.

**Comment by kwonoj** [comment]
I'm hesitant to do so for now, since we're actively moving and there are lot of changes being applied. Publishing into public means we are under responsibility to maintain api surface, but given we already have lots of things to deal with (swc_core / swc, ...) this should wait for now.
