### ISSUE TITLE
npm js plugin add @swc/core peer dependencies?

### ISSUE THREAD

**Issue by rubioNLB** [swc-project/plugins#188]
for example, loadable plugin update version (rust swc_core v0.78.x dependency version update) , if project don't update @swc/core(rust swc_core v0.76.x). local build failed. 
then update @swc/core (same swc_core version v0.78.x with loadable plugin), it works.

is there any auto install process for update npm package for compatiable rust dependency.

**Comment by kwonoj** [comment]
This is out of scope question, plugin pkg itself does not have way to control how user installs other pkgs.
