### ISSUE TITLE
Can we use a feature to enable `plugin-mode`

### ISSUE THREAD

**Issue by JSerFeng** [swc-project/plugins#195]
I have a repo which enable `plugin-rt` feature of `swc_core`, in order to use wasm plugins, the repo also has some builtins plugins, like `swc_loadable_component`.

However `swc_loadable_component` enables `plugin-mode` by default. So that `plugin-rt` and `plugin-mode` is enabled at the same time.

Wondering if we can make `plugin-mode` in `swc_loadable_component` an optional feature, and only enable that feature when publishing to npm

**Comment by kwonoj** [comment]
Plugin runner, host can only enable -rt. The actual plugin, can enable -mode. Those cannot / should not be enabled in a single binary in any case.

**Comment by kwonoj** [comment]
> optional feature, and only enable that feature when publishing to npm

And no, we don't have plan to adjust plugin to compatible to be used in the host currently.
