### ISSUE TITLE
[JEST] Can't instantiate the class directly after definition

### ISSUE THREAD

**Issue by jean-smaug** [swc-project/plugins#198]
👋  Hi,

I'm currently setting up SWC on a project and I was able to make it work with Webpack 5 and the `swc-loader` 🎉 

I'm encountering an issue when trying to use it with Jest.

I have some services that are in an external library. This lib is transpiled on application's side.
So in the `jest.config.ts` I'm doing the following transformation : 

```js
module.exports = {
...
  transformIgnorePatterns: [
    `node_modules/(?!(?:.pnpm/)?(${["myLibrary", "anotherLib"].join('|')}))`,
  ],
...
};
```

A service looks like the following 👇 

```js
export const myService = new (class MyService {...})();
```

When I try to run Jest i'm facing the following error

```
ReferenceError: MyService is not defined
```

A workaround that I found was to change the syntax of the service to

```js
class MyService {...}
export const myService = new MyService();
```

Do you have the explanation of why it's working well with `swc-loader` but not Jest ? 😄 
Is it something known , due to Jest ?

Thanks.

**Comment by kdy1** [comment]
Please file an issue on the main swc repository with the input file containing 
```js
export const myService = new (class MyService {...})();
```

I think this is a bug of the class transform
