### ISSUE TITLE
failed to get the node_modules path when using @swc/plugin-emotion

### ISSUE THREAD

**Issue by leonard-henriquez** [swc-project/plugins#227]
When I use @swc/plugin-emotion in my monorepo, i get the following error "failed to get the node_modules path"
How can I specify the path to node_module directory ?

**Comment by kwonoj** [comment]
Plugin does not have such option, and also plugin does not read the actual filesystem under node_modules. If you believe this is a plugin issue, please provide a minimal reproducible codes to point out plugin's behavior.
