### ISSUE TITLE
relay is failing on windows

### ISSUE THREAD

**Issue by sibelius** [swc-project/plugins#231]
```jsx
Module not found: Error: Can't resolve '__generated__/PrintersListQuery.graphql.ts' in 'app\src\renderer'
```

```
Did you mean './__generated__/PrintersListQuery.graphql.ts'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
```

**Comment by araujobarret** [comment]
I have a similar issue in my CircleCI runner and MacOS too:
```
Cannot find module '/home/circleci/project/src/__generated__/to.graphql.ts' from 'src/app/Scenes/ArtistShows/ArtistShows2.tsx'
```
where in the original file the imports related imports are:
```
import { ArtistShows2Query } from "__generated__/ArtistShows2Query.graphql"
import { ArtistShows2_artist$data } from "__generated__/ArtistShows2_artist.graphql"
```

Without SWC everything is working, just to be clear.

**Comment by kdy1** [comment]
Can you provide a repro?

**Comment by sibelius** [comment]
Try here https://github.com/sibelius/relay-workshop

**Comment by kdy1** [comment]
Can you provide a minimal reproduction, or at least instructions to see output files?

**Comment by sibelius** [comment]
Here are the instructions

gh clone sibelius/relay-workshop
yarn
yarn relay (generate the artifacts)
yarn web - it will throw error on windows

**Comment by freiksenet** [comment]
The problem is that it's lacking a `./` at the beginning of import when the actual import has it.

Here is a fix to add option to do it, in case someone depends on the behavior of not having current directory.

https://github.com/swc-project/plugins/pull/273
