### ISSUE TITLE
`emotion`: background url(//domain.com/~~) failed

### ISSUE THREAD

**Issue by bestseob93** [swc-project/plugins#258]
When using background: url('//') without a protocol, it compiles into an incorrect value.

```
styled.div`
  background-image: url('//domain.com/image.png');
`
```

in html
<img width="380" alt="image" src="https://github.com/swc-project/plugins/assets/18053223/45da5aae-8833-4375-999a-6d1b43e2267f">

**Comment by kdy1** [comment]
What's the plugin are you using?

**Comment by bestseob93** [comment]
> What's the plugin are you using?

I used next v14, and the problem occurs when the compiler emotion true option is set to next.config.js. and this also occurs in next v13.4.7.
