### ISSUE TITLE
styled-components plugin not using display_name_and_id

### ISSUE THREAD

**Issue by nickskotny** [swc-project/plugins#30]
While attempting to use the newly published styled-components plugin, I noticed there is no addition of `display_name_and_id` as there is currently in the Next.js codebase. Curious if this functionality was intentionally left out? My team is currently switching over to SWC (without Next) and we currently rely on the `displayName` functionality of the existing babel plugin.

[Current state of plugin](https://github.com/swc-project/plugins/blob/main/packages/styled-components/src/lib.rs):
```rs
    let mut pass = chain!(
        analyzer(config.clone(), state.clone()),
        transpile_css_prop()
    );
```

[Next codebase](https://github.com/vercel/next.js/blob/canary/packages/next-swc/crates/styled_components/src/lib.rs):
```rs
/// Only [analyzer] and [display_name_and_id] is implemented.
pub fn styled_components(file: Arc<SourceFile>, config: Config) -> impl Fold + VisitMut {
    let state: Rc<RefCell<State>> = Default::default();
    let config = Rc::new(config);

    chain!(
        analyzer(config.clone(), state.clone()),
        display_name_and_id(file, config, state),
        transpile_css_prop()
    )
}
```

**Comment by kdy1** [comment]
I excluded it because of `Arc<SourceFile>`, but I'll check how it's actually used.
Maybe we can reduce requirement.

**Comment by kdy1** [comment]
Oh it only uses filename and hash
