### ISSUE TITLE
Update major version of `swc_core` for plugins at same time as `@swc/core`

### ISSUE THREAD

**Issue by rakleed** [swc-project/plugins#359]
Please update the major version of `swc_core` for plugins simultaneously with `@swc/core`. I have now installed `@swc/plugin-styled-components` v4.0.0, but since it also expects `swc_core` version 4, it does not work with the current `@swc/core` v1.7.42, because it still has version 3 of core.

Error:
`1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See the documentation for compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.`

**Comment by kdy1** [comment]
No it’s not possible.
Use plugins.swc.rs

**Comment by kdy1** [comment]
Wasm plugins are experimental

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/issues/9711
