### ISSUE TITLE
[styled-components] SWC Plugin Fails with "wasm plugin bytecheck failed"

### ISSUE THREAD

**Issue by saengmotmi** [swc-project/plugins#375]
**Describe the bug**

While using `@swc/plugin-styled-components` in a Vite project, the SWC plugin fails with the following error message:

```
1:42:49 PM [vite] Internal server error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/.../src/main.tsx")'

Caused by:
    0: failed to invoke `/Users/.../.yarn/unplugged/@swc-plugin-styled-components-npm-6.0.2-13cbf19855/node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm` as js transform plugin at /Users/.../.yarn/unplugged/@swc-plugin-styled-components-npm-6.0.2-13cbf19855/node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm
    1: wasm plugin bytecheck failed "check bytes error: check failed for tuple struct member 0: check failed for struct member pkg_version: pointer overran buffer: ptr 0x289ea0f06b4 size 774909497 in range 0x289ea0f0600..0x289ea0f07a0"
  Plugin: vite:react-swc
  File: /Users/.../src/main.tsx
```

- the setup works correctly without issues. There doesn't seem to be anything unusual in my Vite and package configuration, but since I lack experience with Rust and SWC, I cannot identify the problem.

```ts
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';

export default defineConfig(() => {
  return {
    plugins: [
      react({ plugins: [['@swc/plugin-styled-components', {}]] }),
    ],
  };
});
```

**URL to minimal reproduction**
- I tried `yarn create vite` and install minimal dependencies. but It works.
- anyway, failed to failed to reproduce. sorry.

Please provide a minimal reproduction of the issue. Ideally, the reproduction should only have

```json
{
  "dependencies": {
    "@swc/core": "^1.10.1",
    "styled-components": "^6.1.13"
  },
  "devDependencies": {
    "@swc/plugin-styled-components": "^6.0.2",
    "@vitejs/plugin-react": "^4.3.4",
    "@vitejs/plugin-react-swc": "^3.7.2",
    "vite": "^6.0.3"
  }
}
```

**Expected behavior**
- successfully ran

**Additional context**

- The issue is not resolved by disabling PnP (nodeLinker: node-modules).
- Deleting .yarn/cache and .pnp.* files and reinstalling dependencies did not resolve the issue.

**Comment by kwonoj** [comment]
Have you confirm swc/core and plugin version matches in the supported ranges?

**Comment by saengmotmi** [comment]
it works
```json
"resolutions": {
  "@swc/core": "1.10.1"
}
```

**Comment by GrumpyPirate** [comment]
Had the same issue, and yeah, can confirm, just clearing my `node_modules` and regenerating a fresh lockfile solved the issue. ❤️
