### ISSUE TITLE
Unable to use @swc/plugin-transform-imports

### ISSUE THREAD

**Issue by RomainFallet** [swc-project/plugins#47]
Hello,

I tried to use `@swc/plugin-transform-imports` to transform my relative TypeScript imports such as: 

`import * as utils from './utils'`

To:

`import * as utils from "./utils.js"`

With this configuration into `./swrc`:

```
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2022",
    "experimental": {
      "plugins": [
        [
          "@swc/plugin-transform-imports",
          {
            "./utils": {
              "transform": "./utils.js"
            }
          }
        ]
      ]
    }
  },
  "module": {
    "type": "es6"
  },
  "sourceMaps": true,
  "minify": true
}
```

But imports are not changed and there is no error. What am I doing wrong ?

You can find the reproduction repository here: https://github.com/RomainFallet/swc-transform-plugin-issue

Thanks for the help.

**Comment by tientm-dsv** [comment]
Does anyone have a solution? I also met this issue too.

**Comment by yuhr** [comment]
Same here. I'm using the following option with `https​://esm.sh/​@swc/wasm-web​@1.3.66`:

```typescript
{
	module: { type: "es6" },
	jsc: {
		target: "es2022",
		parser: { syntax: "typescript", tsx: true, dynamicImport: true },
		transform: { react: { runtime: "automatic", importSource: "react" } },
		experimental: {
			plugins: [["transform-imports", { "^(https:.+)$": { transform: "/api/modules/${1}" } }]],
		},
	},
}
```

**Comment by yuhr** [comment]
Gotcha, this is the problem in my case: <https://github.com/swc-project/swc/issues/3934>.

**Comment by yuhr** [comment]
FWIW I managed to get it to work by using `parse` before `transform`:

```typescript
const ast = await parse(content, {
	syntax: "typescript",
	tsx: true,
	dynamicImport: true,
	target: "es2022",
})
for (const node of ast.body) {
	if (node.type === "ImportDeclaration") {
		node.source.value = node.source.value.replace(/^(https:.+)$/, "/api/modules/$1")
		node.source.raw = `"${node.source.value}"`
	}
}
const { code } = await transform(ast, { ...options })
```

**Comment by rlmcneary2** [comment]
Needed this capability today to convert import names from a ".ts" extension to a ".js" extension. After perusing the code I came up with this configuration to do that:

```json
{
  "jsc": {
    "experimental": {
      "plugins": [
        [
          "@swc/plugin-transform-imports",
          { "^(.*?)(\\.ts)$": { "transform": "{{matches.[1]}}.js" } }
        ]
      ]
    },
  },
}
```
- The "key" in the options passed to the plugin is going to be used as a regex and it will be passed the import path for comparison.
- The value of `transform` is a [handlebars](https://handlebarsjs.com/) template. The template renderer is passed a HashMap that contains a `matches` property. This property contains the regex capture groups in an array (0 is the matched string). In the example above the path without an extension is in element 1 of `matches`.

Anyway the configuration above does the following conversion:

```ts
// input: before transpilation
import { fubar } from "../foo/bar.ts";
```

```ts
// output: after transpilation
import { fubar } from "../foo/bar.js";
```

**Comment by Roma-Kyrnis** [comment]
Hi!
For me, it's working only with 
``` typescript 
import { authConversation, deAuthConversation } from './conversations/auth.ts';
```
imports
But with 
```typescript
import ua from '../config/locales/ua.ts';
``` 
it does not work.

And for index.ts files, it's working okay. But then something transforms import from 
```typescript
 import { deAuthHears } from './hears/index.ts';
```
to
```typescript
import { deAuthHears } from './hears';
```

But I need a full path to work with ESM runner

Does someone have an idea why?

I'm using a .swrrc file with settings

``` JSON
{
  // "$schema": "https://json.schemastore.org/swcrc",
  "exclude": [
    "node_modules/"
  ],
  "jsc": {
    "target": "esnext",
    "paths": {
      "*/index.js": ["*", "/index.js"]
    },
    "baseUrl": "./src/",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true,
      "dts": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "experimental": {
      "plugins": [
        [
          "@swc/plugin-transform-imports",
          {
            "^(.*?)(\\.ts)$": {
              "skipDefaultConversion": true,
              "transform": "{{matches.[1]}}.js"
            }
          }
        ]
      ]
    }
  },
  "module": {
    "type": "nodenext"
  }
}
```

**Comment by andkulakov** [comment]
@Roma-Kyrnis in case you're still having issue with compiling
```
import { deAuthHears } from './hears/index.ts';
```
to
```
import { deAuthHears } from './hears';
```
I found this option https://swc.rs/docs/configuration/modules#resolvefully
so you need to add it to your config file
```
"module": {
    "type": "nodenext",
    "resolveFully": true
  }
```

**Comment by kdy1** [comment]
Closing as it's not for appending extension

**Comment by dr2009** [comment]
> Hi! For me, it's working only with
> 
> ```ts
> import { authConversation, deAuthConversation } from './conversations/auth.ts';
> ```
> 
> imports But with
> 
> ```ts
> import ua from '../config/locales/ua.ts';
> ```
> 
> it does not work.
> 
> And for index.ts files, it's working okay. But then something transforms import from
> 
> ```ts
>  import { deAuthHears } from './hears/index.ts';
> ```
> 
> to
> 
> ```ts
> import { deAuthHears } from './hears';
> ```
> 
> But I need a full path to work with ESM runner
> 
> Does someone have an idea why?
> 
> I'm using a .swrrc file with settings
> 
> ```json
> {
>   // "$schema": "https://json.schemastore.org/swcrc",
>   "exclude": [
>     "node_modules/"
>   ],
>   "jsc": {
>     "target": "esnext",
>     "paths": {
>       "*/index.js": ["*", "/index.js"]
>     },
>     "baseUrl": "./src/",
>     "parser": {
>       "syntax": "typescript",
>       "decorators": true,
>       "dynamicImport": true,
>       "dts": true
>     },
>     "transform": {
>       "legacyDecorator": true,
>       "decoratorMetadata": true
>     },
>     "experimental": {
>       "plugins": [
>         [
>           "@swc/plugin-transform-imports",
>           {
>             "^(.*?)(\\.ts)$": {
>               "skipDefaultConversion": true,
>               "transform": "{{matches.[1]}}.js"
>             }
>           }
>         ]
>       ]
>     }
>   },
>   "module": {
>     "type": "nodenext"
>   }
> }
> ```

add `skipDefaultConversion: true` will be ok.

and this plugin has other options
https://github.com/swc-project/plugins/blob/main/packages/transform-imports/transform/src/lib.rs#L24-L33
```
preventFullImport: boolean,
handleDefaultImport: boolean,
handleNamespaceImport: boolean,
skipDefaultConversion: boolean,
```

**Comment by Elisiac** [comment]
Just in case it helps someone else. I had the same issue, tried to use the plugin and it would miserably fail.
The issue was my config missing the `"baseUrl": "src"` parameter... And it properly resolved everything correctly afterward.

```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2022",
    "baseUrl": "src"
  },
  "module": {
    "type": "nodenext",
    "resolveFully": true
  },
  "exclude": ["node_modules", "tests"]
}
```

With 
```
swc -V

@swc/cli: 0.6.0
@swc/core: 1.11.5

✨  Done in 0.33s.
```
