### ISSUE TITLE
jest pluging to export all functions

### ISSUE THREAD

**Issue by tomdavidson** [swc-project/plugins#66]
Sometimes I (we?) would like to have unit tests for functions that we do not expose. I tend to try to write small functions and only want to export a composite function. But I can only write tests for the exported functions. Also, I tend to like the eslint rule requiring a return type on exported functions but want  to leave all those tiny functions up to inference.

Sooo.... is it feasible for the jest plugin export all the functions in the transpile? This would let me keep the exports (and verbose types) to a minimum but still have small tests to go with my small functions. If this is a welcomed concept, I'd love to learn/co-contrib if anyone can help me get started.

**Comment by kwonoj** [comment]
I personally would consider this deserves a separate plugin i stead of jest plugin attempts to do, regardless of if I agree with idea or not.

**Comment by kdy1** [comment]
Closing as not planned. I don't think this is a something that should be done by jest plugin
