### ISSUE TITLE
@swc/plugin-styled-components crashes with Missing export __get_transform_plugin_core_pkg_diag

### ISSUE THREAD

**Issue by develra** [swc-project/plugins#78]
Thanks for all your hard work on the plugins recently!

.swcrc:
```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dynamicImport": true
    },
    "experimental": {
      "plugins": [
        [
          "@swc/plugin-styled-components",
          {
            "displayName": true,
          }
        ]
      ]
    }
  }
}
```

.package-versions:
```
    "@swc/cli": "^0.1.55",
    "@swc/core": "^1.2.242",
    "@swc/plugin-styled-components": "^1.2.9",
    "@swc/jest": "^0.2.17",
     "swc-loader": "0.2.3",
```

error message:
```
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/some_project/index.ts")'

Caused by:
    Missing export __get_transform_plugin_core_pkg_diag', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.218.4/src/plugin.rs:216:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/some_project/index.ts")'
```

Unfortunately still a private project, but let me know if I can provide any additional info for debugging.

**Comment by kwonoj** [comment]
This is due to we made one another breaking change https://github.com/swc-project/swc/pull/5591, which will be resolved once new version of `@swc/core` released.

**Comment by develra** [comment]
> This is due to we made one another breaking change [swc-project/swc#5591](https://github.com/swc-project/swc/pull/5591), which will be resolved once new version of `@swc/core` released.

Great! Thank you for the quick reply - is there a version of @swc/core where I would expect it to work? I can also just wait though - no hurry.

**Comment by kwonoj** [comment]
It is not released yet. I'll check if new version can be released in a day or two.

**Comment by kdy1** [comment]
@kwonoj  #5591 is released

@develra Please update your plugin

**Comment by kdy1** [comment]
It's fixed by https://github.com/swc-project/plugins/pull/77

**Comment by develra** [comment]
@kdy1 - that's good to here, but I must be missing something. 
I think that 1.2.242 is the latest `@swc/core` and 
1.2.9 is latest for `@swc/plugin-styled-components` 

I had tried this before, so a chance I have some old cached thing around - any advice on how to proceed? Thanks again!

**Comment by kdy1** [comment]
You can remove `.swc`

**Comment by develra** [comment]
Thank you - I tried that with no luck.

I put together a minimal project to reproduce the issue:
https://github.com/develra/swc-plugin-issue-78

**Comment by sumanbh** [comment]
I have the same issue - had to temporarily downgrade back to `@swc/core@1.2.241` to get it working.

**Comment by develra** [comment]
This is working well for me now - thank you! 
FWIW we needed to use the 'new' styled-components export style to get it working - see [this babel issue](https://github.com/styled-components/babel-plugin-styled-components/issues/261) for details

**Comment by HashemKhalifa** [comment]
> This is working well for me now - thank you! FWIW we needed to use the 'new' styled-components export style to get it working - see [this babel issue](https://github.com/styled-components/babel-plugin-styled-components/issues/261) for details

Facing the same issue here!
